### ISSUE TITLE
Bootstrap: On individual publisher page, About Me tab is highlighted

### ISSUE THREAD

**Issue by danieljsmarda** [juandigomez/cs329e-idb#18]
If you click on the Publishers tab then click on an individual publisher, you'll notice that on the page for the individual publisher, the "About Me" tab is highlighted. For consistency, I think either no tab or the Publisher tab should be highlighted.

**Comment by cew2882** [comment]
Should be fixed and pushed to GitHub. For consistency and ease of navigation, individual book, author, publisher pages have nothing highlighted (to get back to main book, author, publisher pages)
